apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: flnqgw0me-python
  janus-idp.io/tekton: flnqgw0me-python
  backstage.io/kubernetes-id: flnqgw0me-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: flnqgw0me-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
