apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: flnqgw0me-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:c24f1bc409a86ddcc5c8810fe9111d62a42006a9@sha256:a1308c1b36c7d36b431c024e534e1a50a58675fa7e7bb4b45d7846ddfeec4875
          name: container-image
